This script can be used to render the generated point cloud with specific camera parameters

In [39]:
import src.renderer as renderer
import src.render_point_cloud as renderer2
import src.utility as util
import cv2
import src.Rotation_matrix as rotation
import os
import numpy as np
os.environ['PYOPENGL_PLATFORM'] = 'egl'

In [40]:
# load the aligned multi-view model
id = 212
expression = "1_neutral"
mview_mesh = os.path.join("./demo_output",str(id)+'_'+expression+"_"+"canonical.ply")


In [41]:
# set camera parameters
K = np.array([[1000, 0, 128],
              [0, 1000, 128],
              [0, 0, 1]], dtype=np.float64)

R =np.asarray([[1,  0,  0],
                [0, -1,  0],
                [ 0, 0,  -1]])
t = [0,0,1200]
euler_vector = rotation.rotationMatrixToEulerAngles(R)
euler_vector

array([3.14159265, 0.        , 0.        ])

In [42]:

r = [3.14159, 0, 0]
euler_vector = np.asarray(r)

In [43]:
#convert euler angle to rotation matrix
rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
rotation_matrix

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.00000000e+00, -2.65358979e-06],
       [ 0.00000000e+00,  2.65358979e-06, -1.00000000e+00]])

In [44]:
mesh_pose = [[1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 0]]

rotation.rotationMatrixToEulerAngles(np.array(mesh_pose))

array([0., 0., 0.])

In [56]:
#rotation around combination of pitch and yaw
path = "./rotation/rotation_pitch_yaw_x_y"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    r[0] = r[0]+0.005
    r[1] = r[1]+0.005

In [46]:
path = "./rotation/rotation_pitch_yaw_x_y_negative"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    r[0] = r[0]-0.005
    r[1] = r[1]-0.005
   

In [47]:
#rotation around pitch
path = "./rotation/rotation_pitch_x"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
j = 0
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    r[0] = r[0]+0.005
    
    

In [48]:
path = "./rotation/rotation_pitch_x"+str(id)+'_'+expression+'_'+"negative"
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
j = 0
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    r[0] = r[0]-0.005

In [49]:
path = "./rotation/rotation_yaw_y"+str(id)+'_'+expression+'_'+"negative"
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
j = 0
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+"_"+str(i)+".jpeg", rend_mview_model)
    r[1] = r[1]-0.005
    

In [50]:
path = "./rotation/rotation_yaw_y"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
j = 0
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+"_"+str(i)+".jpeg", rend_mview_model)
    r[1] = r[1]+0.005
    

In [51]:
path = "./rotation/rotation_roll_z"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
j = 0
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    r[2] = r[2]+0.005

In [52]:
path = "./rotation/rotation_roll_z"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
j = 0
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    r[2] = r[2]+0.005

In [53]:
#changing translation in x axis. camera moves to the right (plus direction)
path = "./rotation/translation_x"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
t = [0,0,1200]
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]
    
    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    t[0] = t[0]+0.20

In [54]:
#changing translation in y axis. camera moves upward (plus direction)
path = "./rotation/translation_y"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
t = [0,0,1200]
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    t[1] = t[1]+0.20

In [55]:
#changing translation in z axis. camera moves inside (plus direction)
path = "./rotation/translation_z"+str(id)+'_'+expression
if not os.path.exists(path):
    os.makedirs(path)
r = [3.14159, 0, 0]
t = [0,0,1200]
for i in range(100):
    euler_vector = np.asarray(r)
    rotation_matrix = rotation.eulerAnglesToRotationMatrix(euler_vector)
    Rt = np.eye(3,4)

    Rt[0][:3]= rotation_matrix[0][:3]
    Rt[0][3] = t[0]

    Rt[1][:3]= rotation_matrix[1][:3]
    Rt[1][3] = t[1]

    Rt[2][:3]= rotation_matrix[2][:3]
    Rt[2][3] = t[2]
  
    h, w = 256, 256
    _, rend_mview_model = renderer2.render_cvcam(mview_mesh, K, Rt, rend_size=(h, w), flat_shading=True)

    text = [str(Rt[0][3]),str(Rt[1][3]), str(Rt[2][3]),str(euler_vector[0]),str(euler_vector[1]), str(euler_vector[2])]
    name = '_'.join(text)
    cv2.imwrite(path+'/'+name+'_'+str(i)+".jpeg", rend_mview_model)
    t[2] = t[2]+2.00